# Generated by Django 4.1.1 on 2022-09-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorama', '0003_alter_dorama_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorama',
            name='image',
            field=models.ImageField(blank=True, upload_to='dorama/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
