# Generated by Django 4.1.1 on 2022-09-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorama', '0004_alter_dorama_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorama',
            name='image',
            field=models.ImageField(blank=True, upload_to='dorama', verbose_name='Изображение'),
        ),
    ]
